baseurl = "https://example.com/"
languageCode = "de-DE"
title = "Carsten Bokemeyer"

# Enable Google Analytics by entering your tracking code
googleAnalytics = ""
theme = "hugo-sustain"

[permalinks]
  post = "/:year/:month/:day/:slug"

[params]
  avatar = "profile_new.png"
  author = "Carsten Bokemeyer"
  description = "Dies ist das Online Portfolio von Carsten Bokemeyer. Zur Zeit arbeitet er als Product Owner in Bonn."

  # Custom assets can be linked with their paths relative to static/
  custom_css = []
  custom_js  = []

[params.Social]
  Github        = ""
  Email         = "info@carsten-bokemeyer.de"
  Twitter       = "carbo86"
  LinkedIn      = "carstenbokemeyer"
  XING          = ""
  Medium        = ""
  RSS           = "blog/index.xml"

## Main Menu
[[menu.main]]
  name = "blog"
  weight = 300
  identifier = "blog"
  url = "/blog/"
[[menu.main]]
  name = "projects"
  identifier = "projects"
  weight = 200
  url = "/projects/"
[[menu.main]]
  name = "about"
  identifier = "about"
  weight = 100
  url = "/about/"
